version: '2'

services:
  insync.merit.core.api:
    image: ${DOCKER_REGISTRY}/${API_IMAGE}:${API_TAG}
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
    networks:
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meritapi-${ENVIRONMENT}.rule=Host(`merit-${ENVIRONMENT}.isg-gateway-integration.com`)"
      - "traefik.http.routers.meritapi-${ENVIRONMENT}.entrypoints=web"      
      
  insync.merit.servicebus.processor:
    image: ${DOCKER_REGISTRY}/${BUS_IMAGE}:${BUS_TAG}
      
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - ${DB_PORT}:1433
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      
networks:
  edge:
    external:
      name: edge
